### ISSUE TITLE
Official guide not available

### ISSUE THREAD

**Issue by jakubkrnac** [luqmanhakimpens/nrf5sdk-createproject#1]
Official guide from Nordic Semiconductor is not available when redirected from the [link](https://devzone.nordicsemi.com/nordic/nordic-blog/b/blog/posts/development-with-gcc-and-eclipse). Is this guide still relevant?

**Comment by luqmanhakimpens** [comment]
I'm sorry to say that Nordic no longer has the official Guide to use Eclipse IDE. This project setup is made prior to SDK version 16. If you find it relevant to your project, go ahead and use it as a reference only. Always refer to the official NRF guide.
